// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get app_name => 'vytalLink';

  @override
  String get connection_code_label => 'Connection Code';

  @override
  String connection_copied_to_clipboard(String label) {
    return '$label copied to clipboard';
  }

  @override
  String get connection_copy_button => 'Copy';

  @override
  String get connection_could_not_connect_default =>
      'Could not connect to server';

  @override
  String get connection_could_not_establish => 'Could not establish connection';

  @override
  String get connection_credentials_info_button => 'Info';

  @override
  String get connection_credentials_info_message =>
      'These credentials are temporary and automatically generated by the backend each time you connect. They provide secure access without storing any sensitive information on your device. New credentials are created for every connection session to ensure maximum security.';

  @override
  String get connection_credentials_info_title => 'About Temporary Credentials';

  @override
  String get connection_credentials_subtitle =>
      'These credentials are temporary and change with each connection';

  @override
  String get connection_credentials_title => 'Temporary Credentials';

  @override
  String get connection_error_network_description =>
      'Unable to connect to the MCP server. Please check your internet connection and try again.';

  @override
  String get connection_error_network_title => 'Connection Failed';

  @override
  String connection_error_prefix(String error) {
    return 'Connection error: $error';
  }

  @override
  String get connection_error_retry => 'Retry Connection';

  @override
  String get connection_error_server_description =>
      'The MCP server is not responding. Please verify the server is running and try again.';

  @override
  String get connection_error_server_title => 'Server Connection Error';

  @override
  String get connection_error_title => 'Connection Error';

  @override
  String get connection_failed_to_establish =>
      'Connection failed - could not establish';

  @override
  String get connection_lost_description =>
      'The connection to the MCP server was lost unexpectedly. Please check your network and try reconnecting.';

  @override
  String get connection_lost_title => 'Connection Lost';

  @override
  String get connection_lost_unexpectedly => 'Connection lost unexpectedly';

  @override
  String get connection_lost_with_server => 'Connection lost with server';

  @override
  String get connection_not_connected => 'Not connected to backend';

  @override
  String get connection_password_label => 'Connection Word';

  @override
  String get connection_retry_button => 'Retry';

  @override
  String get connection_section_title => 'Connection Credentials';

  @override
  String get credentials_copied_to_clipboard =>
      'Credentials copied to clipboard';

  @override
  String get credentials_keep_app_open => 'Keep app open and device unlocked';

  @override
  String get credentials_pin_label => 'PIN';

  @override
  String credentials_text(String word, String pin) {
    return 'Word: $word • PIN: $pin';
  }

  @override
  String get credentials_word_label => 'WORD';

  @override
  String error(String text) {
    return 'Error: $text';
  }

  @override
  String get error_button_ok => 'Ok';

  @override
  String get error_button_retry => 'Retry';

  @override
  String get error_no_internet_connection_error_description =>
      'You have no internet connection';

  @override
  String get error_no_internet_connection_error_title => 'Error';

  @override
  String get error_unknown_error_description => 'Something went wrong!';

  @override
  String get error_unknown_error_title => 'Ops!';

  @override
  String get health_client_config_failed => 'Failed to configure health client';

  @override
  String get health_data_unavailable => 'Health data unavailable';

  @override
  String get health_permission_required => 'Health permission required';

  @override
  String get home_button_start_server => 'Start MCP Server';

  @override
  String get home_button_starting => 'Starting...';

  @override
  String get home_button_stop_server => 'Stop MCP Server';

  @override
  String get home_button_stopping => 'Stopping...';

  @override
  String get home_description_error =>
      'Unable to connect to the MCP server. Please check your connection and try again.';

  @override
  String get home_description_offline =>
      'Ready to start the MCP server on this device';

  @override
  String get home_description_running =>
      'MCP server is active and ready to receive connections';

  @override
  String get home_description_starting =>
      'Initializing MCP server and binding to port...';

  @override
  String get home_description_stopping =>
      'Shutting down server and closing connections...';

  @override
  String home_endpoint_label(String endpoint) {
    return 'Endpoint: $endpoint';
  }

  @override
  String home_server_ip_label(String ipAddress) {
    return 'Server IP: $ipAddress';
  }

  @override
  String get home_status_error => 'Connection Error';

  @override
  String get home_status_offline => 'MCP Server Offline';

  @override
  String get home_status_running => 'MCP Server Running';

  @override
  String get home_status_starting => 'Starting Server...';

  @override
  String get home_status_stopping => 'Stopping Server...';

  @override
  String get home_title => 'MCP Server Control';
}
